---
- name: Write Hetzner token file (optional; we inline env above)
  ansible.builtin.copy:
    dest: "{{ zfs_pool_root }}/nomad/secrets/hetzner_token"
    content: "{{ hetzner_api_key }}\n"
    mode: '0600'

- name: Render Traefik job file
  ansible.builtin.template:
    src: traefik.nomad.j2
    dest: "{{ zfs_pool_root }}/nomad/jobs/traefik.nomad"
    mode: '0644'
    owner: nomad
    group: nomad

- name: Render Hello job file
  ansible.builtin.template:
    src: hello.nomad.j2
    dest: "{{ zfs_pool_root }}/nomad/jobs/hello.nomad"
    mode: '0644'
    owner: nomad
    group: nomad

- name: Check if Traefik job is running
  ansible.builtin.command: nomad job status traefik
  register: traefik_status
  failed_when: false
  changed_when: false

- name: Run Traefik job
  ansible.builtin.command: nomad job run "{{ zfs_pool_root }}/nomad/jobs/traefik.nomad"
  register: traefik_submit
  changed_when: "traefik_submit.rc == 0"
  when: traefik_status.rc != 0 or "Status = running" not in traefik_status.stdout

- name: Check if Hello job is running
  ansible.builtin.command: nomad job status hello
  register: hello_status
  failed_when: false
  changed_when: false

- name: Run Hello job
  ansible.builtin.command: nomad job run "{{ zfs_pool_root }}/nomad/jobs/hello.nomad"
  register: hello_submit
  changed_when: "hello_submit.rc == 0"
  when: hello_status.rc != 0 or "Status = running" not in hello_status.stdout
