---
- name: Install Podman and friends
  ansible.builtin.apt:
    name: "{{ podman_packages }}"
    state: present
    update_cache: true

- name: Enable Podman socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true

- name: Verify podman socket exists
  ansible.builtin.stat:
    path: /run/podman/podman.sock
  register: podman_socket

- name: Fail if podman socket missing
  ansible.builtin.fail:
    msg: "Podman socket not found at /run/podman/podman.sock"
  when: not podman_socket.stat.exists
