---
- name: Install Nomad
  apt:
    name: nomad
    state: present
    update_cache: yes

- name: Write nomad.hcl
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: root
    group: root
    mode: '0644'
  notify: Restart nomad

- name: Ensure host volume directories exist
  file:
    path: "{{ item.value.path }}"
    state: directory
    mode: '0755'
  loop: "{{ nomad_host_volumes | dict2items }}"

- name: Enable & start nomad
  systemd:
    name: nomad
    state: started
    enabled: yes

# Handlers
- name: Restart nomad
  listen: Restart nomad
  systemd:
    name: nomad
    state: restarted
