---
- name: Install Nomad
  ansible.builtin.apt:
    name: nomad
    state: present
    update_cache: true

- name: Create Nomad directories with proper ownership
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: nomad
    group: nomad
  loop:
    - "{{ zfs_pool_root }}/nomad"
    - "{{ zfs_pool_root }}/nomad/traefik-acme"
    - "{{ zfs_pool_root }}/nomad/secrets"
    - "{{ zfs_pool_root }}/nomad/jobs"

- name: Write nomad.hcl
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: root
    group: root
    mode: '0644'
  notify: Restart nomad

- name: Ensure host volume directories exist
  ansible.builtin.file:
    path: "{{ item.value.path }}"
    state: directory
    mode: '0755'
  loop: "{{ nomad_host_volumes | dict2items }}"

- name: Enable & start nomad
  ansible.builtin.systemd:
    name: nomad
    state: started
    enabled: true
