---
- name: Install prerequisites for Docker repository
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker and friends
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Add nomad user to docker group for socket access
  ansible.builtin.user:
    name: nomad
    groups: docker
    append: true
  notify: Restart nomad

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Verify Docker socket exists
  ansible.builtin.stat:
    path: /var/run/docker.sock
  register: docker_socket

- name: Fail if Docker socket missing
  ansible.builtin.fail:
    msg: "Docker socket not found at /var/run/docker.sock"
  when: not docker_socket.stat.exists

- name: Test Docker functionality
  ansible.builtin.command: docker version
  become: true
  register: docker_version
  changed_when: false

- name: Display Docker version
  ansible.builtin.debug:
    var: docker_version.stdout_lines
