---
- name: Ensure base packages are installed
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: true
  tags: ['packages', 'base', 'setup']

- name: Enable NTP via systemd-timesyncd
  ansible.builtin.command: timedatectl set-ntp true
  changed_when: false
  tags: ['time', 'base', 'config']

- name: Create base ZFS directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "{{ zfs_pool_root }}"
    - "{{ zfs_pool_root }}/containers"
    - "{{ zfs_pool_root }}/logs"
  tags: ['directories', 'storage', 'base', 'setup']
